### PR TITLE
update graphql-client gem version

### PR DESCRIPTION
**Pull request by wowremywang**
updated graphql-client gem version

### CODE REVIEW

**Comment by mikeyhew** [comment]
Hmm, looks like it's failing because I haven't configured a test shop for travis yet

**Review by mikeyhew — APPROVED** [review]
The code looks fine though, so I'll merge it

**Comment by wowremywang** [comment]
Thank you @mikeyhew 👍

**Comment by mikeyhew** [comment]
thanks!

**Pull request merged**
